/**
 * PnlJugador.java
 */
package org.itson.GUI;

import org.itson.Dominio.Jugador;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;

/**
 * JPanel que despliega la informacion de un jugador.
 * 
 * @author Alejandro Galindo, Francisco Félix
 */
public class PnlJugador extends javax.swing.JPanel {

    /**
     * Instancia del jugador al desplegar.
     */
    private Jugador jugador;

    /**
     * Crea PnlJugador.
     */
    public PnlJugador(Jugador jugador) {
        initComponents();
        this.setSize(new Dimension(150, 142));
        this.jugador = jugador;
        if(!this.jugador.getRutaAvatar().equalsIgnoreCase("")){
            this.labelAvt.setIcon(new ImageIcon("src\\main\\resources\\img\\" + this.jugador.getRutaAvatar()));
        }
        this.labelNick.setText(this.jugador.getNombre());
        this.labelPtj.setText(this.jugador.getPuntaje() + "");
        if(this.jugador.getColor() != null){
            this.setBackground(Color.decode(this.jugador.getColor()));
        }
    }
    
    /**
     * Establece el jugador.
     * @param jugador 
     */
    public void setJugador(Jugador jugador){
        this.jugador = jugador;
    }
    
    /**
     * Establece el puntaje de un jugador.
     * @param puntaje 
     */
    public void setPuntaje(int puntaje){
        this.jugador.setPuntaje(puntaje);
        this.labelPtj.setText(puntaje + "");
        this.labelPtj.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAvt = new javax.swing.JLabel();
        labelPtj = new javax.swing.JLabel();
        labelNick = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(150, 142));
        setMinimumSize(new java.awt.Dimension(150, 142));
        setPreferredSize(new java.awt.Dimension(150, 142));

        labelAvt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelAvt.setMaximumSize(new java.awt.Dimension(50, 50));
        labelAvt.setMinimumSize(new java.awt.Dimension(50, 50));
        labelAvt.setPreferredSize(new java.awt.Dimension(50, 50));

        labelPtj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPtj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPtj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelPtj.setMaximumSize(new java.awt.Dimension(50, 50));
        labelPtj.setMinimumSize(new java.awt.Dimension(50, 50));
        labelPtj.setPreferredSize(new java.awt.Dimension(50, 50));

        labelNick.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        labelNick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAvt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(labelPtj, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelNick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAvt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPtj, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelNick, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAvt;
    private javax.swing.JLabel labelNick;
    private javax.swing.JLabel labelPtj;
    // End of variables declaration//GEN-END:variables
}